### ISSUE TITLE
请问老大，建立好了容器，手动执行没问题，但是不会定时执行，是何原因？

### ISSUE THREAD

**Issue by fulianbaoBear** [ClassmateLin/jd_scripts#8]

**Comment by miwensheng** [comment]
在conf的文件夹里面有一个crontab.sh，按照大佬的默认定时，放进去以后，还是没按时执行。

**Comment by fulianbaoBear** [comment]
以前老的容器可以跑，升级成新的，跑不了了

**Comment by ClassmateLin** [comment]
crontab有错误,   执行命令更新:  docker exec -itd jd /bin/docker-entrypoint

**Comment by fulianbaoBear** [comment]
大佬，还是执行不了呀~更新了，而且重装了，以为是config错了，就写了一个CK，其他都没动，还是无法自动跑~而且重装后进容器找不到logs，是不是这个原因呢，crontab需要自己手动从shell里cp到conf，不会自动写入~

**Comment by ClassmateLin** [comment]
有没有pull 最新的镜像

**Comment by fulianbaoBear** [comment]
classmatelin/hhl:latest 两天前的最新镜像，刚看了下，是最新的了~

**Comment by ClassmateLin** [comment]
今日修复的，我现在使用是正常的，建议重新建容器。

**Comment by fulianbaoBear** [comment]
删了镜像重新下载，构建后，还是一样，从换新镜像后就没法自动运行了，之前跑的很顺畅~
classmatelin/hhl         latest    667c6f4c2999   2 days ago     828MB
--------------------------------------------------------------------------------
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS                                            NAMES
4ae3810c45c2   classmatelin/hhl:latest   "/bin/docker-entrypo…"   24 minutes ago   Up 24 minutes                                                    jd

难道只有我出问题了。。。。。

**Comment by ClassmateLin** [comment]
######开始执行更新脚本######
代码目录为空, 开始clone代码...
Cloning into '/scripts'...
配置文件不存在, 复制配置文件...
git pull拉取最新代码...
Already up to date.
pip install 安装最新依赖...
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 1)) (3.7.4.post0)
Requirement already satisfied: furl in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: loguru in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 4)) (5.4.1)
Requirement already satisfied: qrcode in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 5)) (7.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 6)) (2.26.0)
Requirement already satisfied: rich in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 7)) (10.6.0)
Requirement already satisfied: pyppeteer in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 8)) (0.2.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 9)) (8.3.1)
Requirement already satisfied: moment in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 10)) (0.12.1)
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 11)) (13.7)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 12)) (4.5.3.56)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (3.10.0.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (21.2.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp->-r /scripts/requirements.txt (line 1)) (3.2)
Requirement already satisfied: six>=1.8.0 in /usr/local/lib/python3.7/site-packages (from furl->-r /scripts/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: orderedmultidict>=1.0.1 in /usr/local/lib/python3.7/site-packages (from furl->-r /scripts/requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (2.0.3)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (2.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (4.61.2)
Requirement already satisfied: websockets<9.0,>=8.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (8.1)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (8.1.0)
Requirement already satisfied: importlib-metadata<3.0.0,>=2.1.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (2.1.1)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (1.4.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata<3.0.0,>=2.1.1->pyppeteer->-r /scripts/requirements.txt (line 8)) (3.5.0)
Requirement already satisfied: pytz>=2018.9 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (2021.1)
Requirement already satisfied: times>=0.7 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (0.7)
Requirement already satisfied: dateparser>=0.7 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (1.0.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/site-packages (from dateparser>=0.7->moment->-r /scripts/requirements.txt (line 10)) (2.8.2)
Requirement already satisfied: regex!=2019.02.19 in /usr/local/lib/python3.7/site-packages (from dateparser>=0.7->moment->-r /scripts/requirements.txt (line 10)) (2021.7.6)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/site-packages (from dateparser>=0.7->moment->-r /scripts/requirements.txt (line 10)) (2.1)
Requirement already satisfied: arrow in /usr/local/lib/python3.7/site-packages (from times>=0.7->moment->-r /scripts/requirements.txt (line 10)) (1.1.1)
Requirement already satisfied: cachetools==4.2.2 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (4.2.2)
Requirement already satisfied: APScheduler==3.6.3 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (3.6.3)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (6.1)
Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.7/site-packages (from APScheduler==3.6.3->python-telegram-bot->-r /scripts/requirements.txt (line 11)) (57.4.0)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/site-packages (from opencv-python-headless->-r /scripts/requirements.txt (line 12)) (1.21.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
更新docker-entrypoint...
更新crontab任务...
no crontab for root
重载crontab配置...
Reloading configuration files for periodic command scheduler: cron.
######更新脚本执行完毕######

**Comment by fulianbaoBear** [comment]
建立是一样的~
后面我直接docker exec -it jd /bin/docker-entrypoint
显示如下：
--------------------------------------------------------------
######开始执行更新脚本######
日志目录不存在, 创建目录...
git pull拉取最新代码...
Already up to date.
pip install 安装最新依赖...
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 1)) (3.7.4.post0)
Requirement already satisfied: furl in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: loguru in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 4)) (5.4.1)
Requirement already satisfied: qrcode in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 5)) (7.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 6)) (2.26.0)
Requirement already satisfied: rich in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 7)) (10.6.0)
Requirement already satisfied: pyppeteer in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 8)) (0.2.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 9)) (8.3.1)
Requirement already satisfied: moment in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 10)) (0.12.1)
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 11)) (13.7)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 12)) (4.5.3.56)
Requirement already satisfied: ujson in /usr/local/lib/python3.7/site-packages (from -r /scripts/requirements.txt (line 13)) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (21.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (3.10.0.0)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.7/site-packages (from aiohttp->-r /scripts/requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: six>=1.8.0 in /usr/local/lib/python3.7/site-packages (from furl->-r /scripts/requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: orderedmultidict>=1.0.1 in /usr/local/lib/python3.7/site-packages (from furl->-r /scripts/requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (1.26.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/site-packages (from requests->-r /scripts/requirements.txt (line 6)) (2.0.3)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (2.9.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/site-packages (from rich->-r /scripts/requirements.txt (line 7)) (0.4.4)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (4.61.2)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (1.4.4)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (8.1.0)
Requirement already satisfied: importlib-metadata<3.0.0,>=2.1.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (2.1.1)
Requirement already satisfied: websockets<9.0,>=8.1 in /usr/local/lib/python3.7/site-packages (from pyppeteer->-r /scripts/requirements.txt (line 8)) (8.1)
Requirement already satisfied: dateparser>=0.7 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (1.0.0)
Requirement already satisfied: pytz>=2018.9 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (2021.1)
Requirement already satisfied: times>=0.7 in /usr/local/lib/python3.7/site-packages (from moment->-r /scripts/requirements.txt (line 10)) (0.7)
Requirement already satisfied: APScheduler==3.6.3 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (3.6.3)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (6.1)
Requirement already satisfied: cachetools==4.2.2 in /usr/local/lib/python3.7/site-packages (from python-telegram-bot->-r /scripts/requirements.txt (line 11)) (4.2.2)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.7/site-packages (from APScheduler==3.6.3->python-telegram-bot->-r /scripts/requirements.txt (line 11)) (2.1)
Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.7/site-packages (from APScheduler==3.6.3->python-telegram-bot->-r /scripts/requirements.txt (line 11)) (57.4.0)
Requirement already satisfied: numpy>=1.14.5 in /usr/local/lib/python3.7/site-packages (from opencv-python-headless->-r /scripts/requirements.txt (line 12)) (1.21.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/site-packages (from dateparser>=0.7->moment->-r /scripts/requirements.txt (line 10)) (2.8.2)
Requirement already satisfied: regex!=2019.02.19 in /usr/local/lib/python3.7/site-packages (from dateparser>=0.7->moment->-r /scripts/requirements.txt (line 10)) (2021.7.6)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata<3.0.0,>=2.1.1->pyppeteer->-r /scripts/requirements.txt (line 8)) (3.5.0)
Requirement already satisfied: arrow in /usr/local/lib/python3.7/site-packages (from times>=0.7->moment->-r /scripts/requirements.txt (line 10)) (1.1.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
更新docker-entrypoint...
更新cron任务...
重启cron进程...
[ ok ] Restarting periodic command scheduler: cron[....] Stopping periodic command scheduler: cron.
[ ok ] Starting periodic command scheduler: cron.
######更新脚本执行完毕######
-----------------------------------------------------------------------------------------------------------------
但是看目录还是没有logs文件夹

root@8fe19715e53e:/scripts# ls
Dockerfile	  dj_bean_manor.py	  jd_beauty.py		jd_esports_manager.py  jd_joy_feed.py	      jd_sign_collection.py   jr_pet_pig.py	test
README.md	  dj_bean_manor_water.py  jd_big_winner.py	jd_factory.py	       jd_joy_park.py	      jd_small_home.py	      jx_cfd.py		update_share_code.py
check_cookies.py  dj_fruit.py		  jd_burning_summer.py	jd_farm.py	       jd_lottery_bean.py     jd_smash_golden_egg.py  jx_factory.py	utils
clean_log.py	  dj_fruit_collect.py	  jd_cash.py		jd_gold_creator.py     jd_lucky_turntable.py  jd_try.py		      jx_farm.py
conf		  get_jd_cookies.py	  jd_collar_bean.py	jd_good_morning.py     jd_planting_bean.py    jd_wishing_pool.py      requirements.txt
config.py	  jd_bean_change.py	  jd_cute_pet.py	jd_joy.py	       jd_ranking_list.py     jr_daily_take_goose.py  shell
dj_bean.py	  jd_bean_indiana.py	  jd_earn_bean.py	jd_joy_exchange.py     jd_shark_bean.py       jr_money_tree.py	      static

**Comment by ClassmateLin** [comment]
logs不影响, python运行执行会创建。 crontab -l

**Comment by fulianbaoBear** [comment]
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
8fe19715e53e   jd        0.00%     6.531MiB / 7.747GiB   0.08%     356kB / 23.6kB    0B / 381kB       4

**Comment by fulianbaoBear** [comment]
我再试试吧，感觉就是不运行，谢谢大佬了~

**Comment by ClassmateLin** [comment]
https://github.com/ClassmateLin/jd_scripts/releases/download/untagged-a49133260684a1048b3f/jd.tar.gz

**Comment by kissyouhunter** [comment]
我这里感觉定时也没有运行 
前两天还有机器人的通知呢
这两天啥消息都没有
手动执行  倒是发来消息给bot

**Comment by fulianbaoBear** [comment]
谢谢大佬，我试下

**Comment by ClassmateLin** [comment]
> 我这里感觉定时也没有运行
> 前两天还有机器人的通知呢
> 这两天啥消息都没有
> 手动执行 倒是发来消息给bot

这两天确实没有运行。今天更新了crontab。需要手动执行容器更新脚本，更新完就可以了。

**Comment by kissyouhunter** [comment]
> > 我这里感觉定时也没有运行
> > 前两天还有机器人的通知呢
> > 这两天啥消息都没有
> > 手动执行 倒是发来消息给bot
> 
> 这两天确实没有运行。今天更新了crontab。需要手动执行容器更新脚本，更新完就可以了。

好的
我也刚更新了下
logs里生成的文件都是空的
也不知道是不是bug

**Comment by ClassmateLin** [comment]
有几个脚本是没有完成的。定时任务貌似也开了。生成的就是空的。

**Comment by kissyouhunter** [comment]
> 有几个脚本是没有完成的。定时任务貌似也开了。生成的就是空的。

okey
还有
jd_bean_indiana_open: true
印第安纳琼斯 你开了吗
我改成true 运行脚本提示说 “配置未开启京豆夺宝功能不运行!
”

**Comment by ClassmateLin** [comment]
jd_bean_indiana: true

**Comment by ClassmateLin** [comment]
> 谢谢大佬，我试下
我重新试了下, 确实是有问题。
docker exec -it jd bash  进去后crontab -e 然后 ESC 输入:wq保存一下。/etc/init.d/cron restart。

**Comment by fulianbaoBear** [comment]
crontab -e后，里面是系统默认的，是对的吗？
restart之后再更新/bin/docker-entrypoint，提示no crontab for root
再之后crontab -l 就一直提示no crontab for root

**Comment by fulianbaoBear** [comment]
今天容器删除重建的不下10次了，镜像也删除，重新拉了次，等大佬更新吧，虚拟机快被我玩烂了~哈哈~
小白一个，不懂怎么改呀~
对了，我是映射出来，有没啥关系？
docker run -dit \
-v /opt/jd/logs:/scripts/logs \
-v /opt/jd/conf:/scripts/conf \
--name jd \
--restart always \
classmatelin/hhl:latest

**Comment by fulianbaoBear** [comment]
new crontab file is missing newline before EOF, can't install.

**Comment by ClassmateLin** [comment]
crontab更新的时候有点问题, 修复时间2021-07-28 21:40:00。
7月26号前的镜像不再支持, 请更新到最新镜像。
 如果是在07-26~07-28创建的容器，请手动执行docker exec -it jd /bin/docker-entrypoint更新一次脚本。
也可自行根据项目dockerfile编译镜像。

**Comment by kissyouhunter** [comment]
刚重建了容器
log也正常了

**Comment by fulianbaoBear** [comment]
可算正常了，谢谢大佬~

**Comment by TurquoiseA** [comment]
> crontab -e后，里面是系统默认的，是对的吗？
> restart之后再更新/bin/docker-entrypoint，提示no crontab for root
> 再之后crontab -l 就一直提示no crontab for root

大佬可以给一个修改cron的例子吗？比如说具体是在哪一个文件中添加自定义的cron，格式大概是怎样的，谢谢了！

**Comment by TurquoiseA** [comment]
> 可算正常了，谢谢大佬~

请问大佬可以分享一个docker-compose的编写例子吗？
